# ============================================
# Framework de Automação - Configuração Padrão
# ============================================

# ---------------- Ambiente ----------------
app.base.url=https://web-premio-empreendedor-sabesp.dev.internal.solutis.xyz/

# ---------------- Browser ----------------
browser=chrome
browser.headless=false
browser.implicit.wait=10
browser.page.load.timeout=30

# ---------------- Timeouts ----------------
wait.explicit.timeout=10
wait.polling.interval=500

# ---------------- Credenciais ----------------
login.username=meuUsuario
login.password=minhaSenha
login.invalid.username=usuario_invalido
login.invalid.password=senha_invalida

# ---------------- Relatório ----------------
report.screenshot.on.failure=true
report.path=target/cucumber-reports




