# config.properties
browser=chrome
driver=chrome
webdriver.chrome.driver=C:/Drivers01/chromedriver.exe
webdriver.gecko.driver=C:/Drivers01/geckodriver
login.username=meuUsuario
login.password=minhaSenha




